# configs/model_config.yaml
# 모델 아키텍처 상세 설정 (선택사항)

architecture:
  # VAE 설정 (frozen, 변경 불가)
  vae:
    type: "AutoencoderOobleck"
    downsampling_rate: 512
    latent_channels: 64
  
  # Text Encoder 설정 (frozen, 변경 불가)
  text_encoder:
    type: "T5EncoderModel"
    model_name: "google/t5-base"
    max_length: 512
  
  # Structure-Conditioned DiT 설정
  transformer:
    type: "StructureConditionedDiT"
    base_config:
      hidden_size: 1024
      num_heads: 16
      depth: 24
      mlp_ratio: 4.0
      dropout: 0.0
      attention_dropout: 0.0
    
    structure_integration:
      method: "cross_attention"
      cross_attention_layers: 8  # depth // 3
      use_gating: true
      
# 추론 설정
inference:
  num_inference_steps: 100
  guidance_scale: 7.0
  default_negative_prompt: "low quality, distorted, noise"
  
  # 생성 길이 제한
  min_duration: 1.0   # 초
  max_duration: 180.0 # 초 (3분)
  
  # 메모리 최적화
  enable_attention_slicing: true
  enable_vae_slicing: true
