# Training configuration
project_name: "structure-aware-stable-audio"

data:
  train_csv: "./data/train.csv"
  val_csv: "./data/val.csv"
  sample_rate: 44100
  segment_duration: 30.0
  hop_duration: 10.0

model:
  vae_model: "stabilityai/stable-audio-open-1.0"
  text_encoder: "google/t5-v1_1-base"
  conditioning_method: "cross_attention"  # or "concat"
  
  structure_encoder:
    embedding_dim: 256
    hidden_dim: 512
    num_layers: 4
    num_heads: 8
    dropout: 0.1
    max_structures: 50
  
  dit:
    hidden_size: 768
    num_heads: 12
    depth: 12
    mlp_ratio: 4.0

training:
  batch_size: 4
  num_epochs: 100
  learning_rate: 0.0001
  min_lr: 0.00001
  weight_decay: 0.01
  gradient_clip: 1.0
  
  num_workers: 4
  log_interval: 100
  val_interval: 1
  checkpoint_dir: "./checkpoints"
  log_dir: "./logs"
  
  use_wandb: true